apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
