apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
  namespace: event-service
type: Opaque
stringData:
  DB_USER: events
  DB_PASSWORD: events
  POSTGRES_USER: events
  POSTGRES_PASSWORD: events
